// <auto-generated />
using System;
using KelimeEzberleme.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KelimeEzberleme.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250517205510_AddWordSentenceTables")]
    partial class AddWordSentenceTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KelimeEzberleme.Models.GuessResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GuessResults", (string)null);
                });

            modelBuilder.Entity("KelimeEzberleme.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriID"));

                    b.Property<string>("KategoriAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KategoriID");

                    b.HasIndex("KategoriAd")
                        .IsUnique();

                    b.ToTable("Kategoriler", (string)null);

                    b.HasData(
                        new
                        {
                            KategoriID = 1,
                            KategoriAd = "Meyve"
                        },
                        new
                        {
                            KategoriID = 2,
                            KategoriAd = "Sebze"
                        },
                        new
                        {
                            KategoriID = 3,
                            KategoriAd = "Nesne"
                        },
                        new
                        {
                            KategoriID = 4,
                            KategoriAd = "Bitki"
                        },
                        new
                        {
                            KategoriID = 5,
                            KategoriAd = "Özne"
                        },
                        new
                        {
                            KategoriID = 6,
                            KategoriAd = "Hayvan"
                        },
                        new
                        {
                            KategoriID = 7,
                            KategoriAd = "Gıda"
                        },
                        new
                        {
                            KategoriID = 8,
                            KategoriAd = "Atmosfer"
                        },
                        new
                        {
                            KategoriID = 9,
                            KategoriAd = "Fiil"
                        });
                });

            modelBuilder.Entity("KelimeEzberleme.Models.LetterStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuessResultId")
                        .HasColumnType("int");

                    b.Property<string>("Letter")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("GuessResultId");

                    b.ToTable("LetterStatuses", (string)null);
                });

            modelBuilder.Entity("KelimeEzberleme.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TokenExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KelimeEzberleme.Models.UserSettings", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("KelimeEzberleme.Models.Word", b =>
                {
                    b.Property<int>("WordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EngWordName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLearned")
                        .HasColumnType("bit");

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TurWordName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WordID");

                    b.HasIndex("KategoriID");

                    b.ToTable("Words", (string)null);
                });

            modelBuilder.Entity("KelimeEzberleme.Models.WordProgress", b =>
                {
                    b.Property<int>("WordProgressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordProgressID"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsLearned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAnswered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextRepeat")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("WordProgressID");

                    b.HasIndex("WordID");

                    b.ToTable("WordProgresses", (string)null);
                });

            modelBuilder.Entity("KelimeEzberleme.Models.WordSample", b =>
                {
                    b.Property<int>("WordSamplesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordSamplesID"));

                    b.Property<int?>("KategoriID")
                        .HasColumnType("int");

                    b.Property<string>("Samples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordID")
                        .HasColumnType("int");

                    b.HasKey("WordSamplesID");

                    b.HasIndex("KategoriID");

                    b.HasIndex("WordID");

                    b.ToTable("WordSamples");
                });

            modelBuilder.Entity("KelimeEzberleme.Models.LetterStatus", b =>
                {
                    b.HasOne("KelimeEzberleme.Models.GuessResult", null)
                        .WithMany("Letters")
                        .HasForeignKey("GuessResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KelimeEzberleme.Models.UserSettings", b =>
                {
                    b.HasOne("KelimeEzberleme.Models.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("KelimeEzberleme.Models.UserSettings", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KelimeEzberleme.Models.Word", b =>
                {
                    b.HasOne("KelimeEzberleme.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriID");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("KelimeEzberleme.Models.WordProgress", b =>
                {
                    b.HasOne("KelimeEzberleme.Models.Word", "Word")
                        .WithMany("WordProgresses")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("KelimeEzberleme.Models.WordSample", b =>
                {
                    b.HasOne("KelimeEzberleme.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriID");

                    b.HasOne("KelimeEzberleme.Models.Word", "Word")
                        .WithMany("Samples")
                        .HasForeignKey("WordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("KelimeEzberleme.Models.GuessResult", b =>
                {
                    b.Navigation("Letters");
                });

            modelBuilder.Entity("KelimeEzberleme.Models.User", b =>
                {
                    b.Navigation("UserSettings")
                        .IsRequired();
                });

            modelBuilder.Entity("KelimeEzberleme.Models.Word", b =>
                {
                    b.Navigation("Samples");

                    b.Navigation("WordProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
